(in-package #:datetime-protocol)

;;;; Date-level recurrence + event-schedule extension points.
;;;;
;;;; Lisp API is CLOS (SCHEDULE, MAP-OCCURRENCES, EVENT-SCHEDULE).
;;;; RFC 5545 RECUR is interchange (PARSE-RRULE / PRINT-RRULE), not the DX.
;;;; Holiday / business-day methods live on the calendar that owns the law.
;;;; Sunrise / Easter / Chinese NY specialize EVENT-SCHEDULE in /calendars.

(define-condition unbounded-schedule (datetime-arithmetic-error)
  ((schedule :initarg :schedule :reader unbounded-schedule-schedule :initform nil))
  (:report (lambda (c s)
             (format s "unbounded schedule~@[: ~a~] — pass :to, :count, or a schedule :until/:count"
                     (datetime-error-message c)))))

(define-condition unknown-event (datetime-error)
  ((source :initarg :source :reader unknown-event-source :initform nil)
   (event :initarg :event :reader unknown-event-event :initform nil))
  (:report (lambda (c s)
             (format s "unknown event ~s for ~s — specialize EVENT-SCHEDULE or REGISTER-EVENT"
                     (unknown-event-event c) (unknown-event-source c)))))

(define-condition unsupported-recurrence (datetime-parse-error) ()
  (:report (lambda (c s)
             (format s "unsupported recurrence~@[: ~a~]~@[ (input ~s)~]"
                     (datetime-error-message c) (datetime-parse-error-input c)))))

;;; --- protocol ------------------------------------------------------------

(defclass schedule ()
  ()
  (:documentation "Generates DATEs (or MOMENTs). Specialize OCCURRENCE-P and
MAP-OCCURRENCES. Combinators and EVENT-SCHEDULE work on any subclass."))

(defun schedulep (x) (typep x 'schedule))

(defgeneric occurrence-date (x)
  (:documentation "Civil DATE of an occurrence (DATE or MOMENT)."))
(defmethod occurrence-date ((d date)) d)
(defmethod occurrence-date ((m moment)) (moment-date m))

(defgeneric occurrence-p (schedule date)
  (:documentation "True when DATE is a civil day generated by SCHEDULE.
COUNT is ignored; UNTIL is honoured."))

(defgeneric map-occurrences (function schedule &key from to count)
  (:documentation "Call FUNCTION with each occurrence in order.
FROM inclusive, TO exclusive (like INTERVAL). FUNCTION receives a DATE
or a MOMENT. Unbounded walk signals UNBOUNDED-SCHEDULE."))

(defgeneric next-occurrence (schedule after &key inclusive)
  (:documentation "First occurrence at/after AFTER."))

(defgeneric previous-occurrence (schedule before &key inclusive)
  (:documentation "Last occurrence at/before BEFORE."))

(defgeneric schedule-origin (schedule)
  (:documentation "Earliest DATE this schedule can emit, or NIL."))
(defmethod schedule-origin ((s schedule)) nil)

(defun occurrences (schedule &key from to count)
  (let ((acc '()))
    (map-occurrences (lambda (x) (push x acc)) schedule
                     :from from :to to :count count)
    (nreverse acc)))

(defmacro do-occurrences ((var schedule &key from to count) &body body)
  `(map-occurrences (lambda (,var) ,@body) ,schedule
                    :from ,from :to ,to :count ,count))

(defun %as-date (x)
  (etypecase x
    (null nil)
    (date x)
    (moment (moment-date x))))

(defmethod next-occurrence ((s schedule) after &key inclusive)
  (let ((found nil)
        (from (%as-date after)))
    (setf from (if inclusive from (date-from-rd (cl:1+ (date-rd from)))))
    (map-occurrences (lambda (x)
                       (setf found x)
                       (return-from next-occurrence x))
                     s :from from :count 1)
    found))

(defmethod previous-occurrence ((s schedule) before &key inclusive)
  (let* ((last nil)
         (origin (schedule-origin s))
         (end (%as-date before))
         (end* (if inclusive (date-from-rd (cl:1+ (date-rd end))) end))
         (from (or origin (date-from-rd (cl:- (date-rd end*) 400)))))
    (when (and origin (cl:< (date-rd end*) (date-rd origin)))
      (return-from previous-occurrence nil))
    (map-occurrences (lambda (x) (setf last x)) s :from from :to end*)
    last))

(defun %ensure-bound (schedule to count until rec-count)
  (if (or to count until rec-count)
      (values to count)
      (restart-case
          (error 'unbounded-schedule :schedule schedule
                 :message "need :to, :count, or a schedule :until/:count")
        (use-count (n)
          :report "Supply a COUNT"
          (values to n))
        (use-until (date)
          :report "Supply an exclusive TO date"
          (values date count)))))

;;; --- event-schedule (extension point) ------------------------------------

(defvar *event-schedule-registry* (make-hash-table :test #'equal)
  "Keys are (SOURCE-KEY . EVENT). SOURCE-KEY is T or a class name.
   Values are (lambda (source &rest keys) schedule).")

(defun register-event (event handler &key (source t))
  "Later rules (holidays, named festivals, …) register here without
editing this file. HANDLER is (lambda (source &key …) schedule)."
  (setf (gethash (cons source event) *event-schedule-registry*) handler)
  event)

(defun %lookup-event (source event)
  (or (gethash (cons (class-name (class-of source)) event) *event-schedule-registry*)
      (and (keywordp source) (gethash (cons source event) *event-schedule-registry*))
      (gethash (cons t event) *event-schedule-registry*)))

(defgeneric event-schedule (source event &key)
  (:documentation "SCHEDULE of EVENT in SOURCE.

EVENT is a keyword. Built-in names (methods in /calendars unless noted):

  :sunrise :sunset :dawn :dusk :midday
  :jewish-sunset :jewish-nightfall
  :islamic-maghrib :islamic-fajr :islamic-isha
  :spring-equinox :autumn-equinox :qingming
  :easter-western :easter-orthodox
  :chinese-new-year :passover :rosh-hashanah
  :eid-al-fitr :eid-al-adha :islamic-new-year
  :holiday :business-day :weekend :new-year

SOURCE owns the rule: an ASTRO-LOCATION, a holiday calendar, :COMPUTUS, or T.
Specialize this generic, or REGISTER-EVENT. Dawn/dusk accept :depression;
Islamic fajr/isha accept :angle."))

(defmethod event-schedule (source event &rest args &key)
  (let ((fn (%lookup-event source event)))
    (if fn
        (apply fn source args)
        (error 'unknown-event :source source :event event))))

;;; --- weekday atoms -------------------------------------------------------

(defparameter *weekday-names*
  '((:monday . 1) (:tuesday . 2) (:wednesday . 3) (:thursday . 4)
    (:friday . 5) (:saturday . 6) (:sunday . 7)))

(defparameter *rfc-weekdays*
  '(("MO" . 1) ("TU" . 2) ("WE" . 3) ("TH" . 4)
    ("FR" . 5) ("SA" . 6) ("SU" . 7)))

(defun weekday-number (weekday)
  (etypecase weekday
    (integer
     (unless (cl:<= 1 weekday 7)
       (error 'datetime-arithmetic-error
              :message (format nil "weekday ~s is not 1..7" weekday)))
     weekday)
    (keyword
     (or (cdr (assoc weekday *weekday-names*))
         (error 'datetime-arithmetic-error
                :message (format nil "unknown weekday ~s" weekday))))))

(defun week-start-rd (date wkst)
  (cl:- (date-rd date) (mod (cl:- (date-day-of-week date) wkst) 7)))

(defun nth-weekday-of-month (year month weekday nth)
  (let ((wd (weekday-number weekday)))
    (if (cl:minusp nth)
        (loop for rd from (fixed-from-date +gregorian+ year month
                                           (days-in-gregorian-month year month))
                downto (fixed-from-date +gregorian+ year month 1)
              for d = (date-from-rd rd)
              when (cl:= (date-day-of-week d) wd) do (cl:incf nth)
              when (cl:zerop nth) return d)
        (loop for rd from (fixed-from-date +gregorian+ year month 1)
                to (fixed-from-date +gregorian+ year month
                                    (days-in-gregorian-month year month))
              for d = (date-from-rd rd)
              when (cl:= (date-day-of-week d) wd) do (cl:decf nth)
              when (cl:zerop nth) return d))))

(defun nth-weekday-of-year (year weekday nth)
  "NTH WEEKDAY in YEAR (RFC YEARLY;BYDAY=2FR = 2nd Friday of the year)."
  (let ((wd (weekday-number weekday)))
    (if (cl:minusp nth)
        (loop for rd from (fixed-from-date +gregorian+ year 12 31)
                downto (fixed-from-date +gregorian+ year 1 1)
              for d = (date-from-rd rd)
              when (cl:= (date-day-of-week d) wd) do (cl:incf nth)
              when (cl:zerop nth) return d)
        (loop for rd from (fixed-from-date +gregorian+ year 1 1)
                to (fixed-from-date +gregorian+ year 12 31)
              for d = (date-from-rd rd)
              when (cl:= (date-day-of-week d) wd) do (cl:decf nth)
              when (cl:zerop nth) return d))))

;;; --- recurrence (RFC 5545 date-level) ------------------------------------

(defclass recurrence (schedule)
  ((freq :initarg :freq :reader recurrence-freq
         :type (member :daily :weekly :monthly :yearly))
   (interval :initarg :interval :reader recurrence-interval :initform 1
             :type (integer 1))
   (start :initarg :start :reader recurrence-start :initform nil)
   (until :initarg :until :reader recurrence-until :initform nil)
   (count :initarg :count :reader recurrence-count :initform nil)
   (weekdays :initarg :weekdays :reader recurrence-weekdays :initform nil)
   (monthdays :initarg :monthdays :reader recurrence-monthdays :initform nil)
   (months :initarg :months :reader recurrence-months :initform nil)
   (setpos :initarg :setpos :reader recurrence-setpos :initform nil)
   (week-start :initarg :week-start :reader recurrence-week-start :initform 1
               :type (integer 1 7))))

(defun recurrencep (x) (typep x 'recurrence))

(defmethod schedule-origin ((r recurrence)) (recurrence-start r))

(defmethod print-object ((o recurrence) stream)
  (print-unreadable-object (o stream :type t)
    (format stream "~a every ~d~@[ from ~a~]"
            (recurrence-freq o) (recurrence-interval o) (recurrence-start o))))

(defun %ensure-date (x label)
  (cond ((null x) nil)
        ((datep x) x)
        (t (error 'datetime-arithmetic-error
                  :message (format nil "~a must be a DATE, got ~s" label x)))))

(defun %ensure-interval (n)
  (unless (and (integerp n) (cl:plusp n))
    (error 'datetime-arithmetic-error
           :message (format nil ":every must be a positive integer, got ~s" n)))
  n)

(defun %as-list (x) (if (and x (not (listp x))) (list x) x))

(defun %weekday-spec (x)
  (cond
    ((or (integerp x) (keywordp x)) (weekday-number x))
    ((and (consp x) (eq (car x) :nth))
     (destructuring-bind (n wd) (rest x)
       (cons n (weekday-number wd))))
    ((and (consp x) (member :weekday x))
     (let ((wd (getf x :weekday)) (n (getf x :nth)))
       (if n (cons n (weekday-number wd)) (weekday-number wd))))
    (t (error 'datetime-arithmetic-error
              :message (format nil "bad weekday spec ~s" x)))))

(defun %month-day (year month day)
  (let ((len (days-in-gregorian-month year month)))
    (cond ((cl:<= 1 day len) (make-date year month day))
          ((cl:< day 0)
           (let ((d (cl:1+ (cl:+ len day))))
             (when (cl:<= 1 d len) (make-date year month d))))
          (t nil))))

(defun %weekdays-in-month (year month spec)
  (if (consp spec)
      (let ((d (nth-weekday-of-month year month (cdr spec) (car spec))))
        (when d (list d)))
      (loop for day from 1 to (days-in-gregorian-month year month)
            for d = (make-date year month day)
            when (cl:= (date-day-of-week d) spec) collect d)))

(defun %apply-setpos (dates setpos)
  (if (null setpos)
      dates
      (let* ((v (coerce dates 'vector)) (n (length v)))
        (loop for p in setpos
              for i = (if (cl:minusp p) (cl:+ n p) (cl:1- p))
              when (and (cl:<= 0 i) (cl:< i n)) collect (aref v i)))))

(defun %filter-date (rec date)
  (let ((months (recurrence-months rec))
        (mdays (recurrence-monthdays rec))
        (wds (recurrence-weekdays rec)))
    (and (or (null months) (member (date-month date) months :test #'eql))
         (or (null mdays)
             (some (lambda (d)
                     (let ((got (%month-day (date-year date) (date-month date) d)))
                       (and got (value= got date))))
                   mdays))
         (or (null wds)
             (some (lambda (spec)
                     (if (consp spec)
                         (let ((nth (nth-weekday-of-month (date-year date)
                                                          (date-month date)
                                                          (cdr spec) (car spec))))
                           (and nth (value= nth date)))
                         (cl:= (date-day-of-week date) spec)))
                   wds))
         t)))

(defun %in-until-p (rec date)
  (let ((u (recurrence-until rec)))
    (or (null u) (cl:<= (date-rd date) (date-rd u)))))

(defun %on-grid-p (rec date)
  (let ((start (recurrence-start rec))
        (interval (recurrence-interval rec)))
    (unless start
      (return-from %on-grid-p (cl:= interval 1)))
    (when (cl:< (date-rd date) (date-rd start))
      (return-from %on-grid-p nil))
    (ecase (recurrence-freq rec)
      (:daily (cl:zerop (mod (cl:- (date-rd date) (date-rd start)) interval)))
      (:weekly
       (cl:zerop (mod (floor (cl:- (week-start-rd date (recurrence-week-start rec))
                                   (week-start-rd start (recurrence-week-start rec)))
                             7)
                      interval)))
      (:monthly
       (cl:zerop (mod (cl:- (cl:+ (cl:* (date-year date) 12) (date-month date))
                            (cl:+ (cl:* (date-year start) 12) (date-month start)))
                      interval)))
      (:yearly
       (cl:zerop (mod (cl:- (date-year date) (date-year start)) interval))))))

(defun %daily-candidates (rec rd)
  (let ((d (date-from-rd rd)))
    (when (%filter-date rec d) (list d))))

(defun %weekly-candidates (rec week-rd)
  (let ((wds (or (recurrence-weekdays rec)
                 (and (recurrence-start rec)
                      (list (date-day-of-week (recurrence-start rec)))))))
    (%apply-setpos
     (sort
      (loop for spec in wds
            for wd = (if (consp spec) (cdr spec) spec)
            for d = (date-from-rd
                     (cl:+ week-rd (mod (cl:- wd (recurrence-week-start rec)) 7)))
            when (and (not (consp spec)) (%filter-date rec d)) collect d)
      #'cl:< :key #'date-rd)
     (recurrence-setpos rec))))

(defun %month-candidates (rec year month)
  (let ((mdays (recurrence-monthdays rec))
        (wds (recurrence-weekdays rec))
        (start (recurrence-start rec)))
    (%apply-setpos
     (sort
      (cond
        ((and mdays wds)
         (loop for spec in wds
               append (remove-if-not
                       (lambda (d)
                         (some (lambda (md)
                                 (let ((x (%month-day year month md)))
                                   (and x (value= x d))))
                               mdays))
                       (%weekdays-in-month year month spec))))
        (mdays
         (loop for md in mdays
               for d = (%month-day year month md)
               when (and d (%filter-date rec d)) collect d))
        (wds
         (loop for spec in wds
               append (remove-if-not (lambda (d) (%filter-date rec d))
                                     (%weekdays-in-month year month spec))))
        (t
         (let ((d (and start (%month-day year month (date-day start)))))
           (when (and d (%filter-date rec d)) (list d)))))
      #'cl:< :key #'date-rd)
     (recurrence-setpos rec))))

(defun %year-candidates (rec year)
  (let ((months (recurrence-months rec))
        (wds (recurrence-weekdays rec))
        (start (recurrence-start rec)))
    (%apply-setpos
     (sort
      (cond
        ((and (null months) wds (some #'consp wds))
         ;; YEARLY;BYDAY=2FR — 2nd Friday of the year (errata 3779).
         (loop for spec in wds
               for d = (if (consp spec)
                           (nth-weekday-of-year year (cdr spec) (car spec))
                           nil)
               when (and d (%filter-date rec d)) collect d))
        (t
         (loop for month in (or months (and start (list (date-month start)))
                                '(1 2 3 4 5 6 7 8 9 10 11 12))
               append (%month-candidates rec year month))))
      #'cl:< :key #'date-rd)
     (recurrence-setpos rec))))

(defmethod occurrence-p ((r recurrence) (date date))
  (and (%on-grid-p r date)
       (%in-until-p r date)
       (let ((cands
               (ecase (recurrence-freq r)
                 (:daily (%daily-candidates r (date-rd date)))
                 (:weekly (%weekly-candidates r (week-start-rd date (recurrence-week-start r))))
                 (:monthly (%month-candidates r (date-year date) (date-month date)))
                 (:yearly (%year-candidates r (date-year date))))))
         (some (lambda (d) (value= d date)) cands))))

(defun %walk-emit (fn rec date from-rd to-rd rule-left query-left)
  "COUNT on the rule is from START. Query COUNT is the window. Values: remaining pair + stop."
  (unless (%in-until-p rec date)
    (return-from %walk-emit (values rule-left query-left nil)))
  (let ((rd (date-rd date))
        (origin-rd (and (recurrence-start rec) (date-rd (recurrence-start rec)))))
    (when (and origin-rd (cl:< rd origin-rd))
      (return-from %walk-emit (values rule-left query-left nil)))
    (when rule-left (cl:decf rule-left))
    (when (and (cl:>= rd from-rd) (or (null to-rd) (cl:< rd to-rd)))
      (funcall fn date)
      (when query-left (cl:decf query-left)))
    (values rule-left query-left
            (or (and rule-left (cl:zerop rule-left))
                (and query-left (cl:zerop query-left))))))

(defun %walk-list (fn rec dates from-rd to-rd rule-left query-left)
  (dolist (d dates (values rule-left query-left nil))
    (multiple-value-bind (rl ql stop)
        (%walk-emit fn rec d from-rd to-rd rule-left query-left)
      (setf rule-left rl query-left ql)
      (when stop (return (values rl ql t))))))

(defmethod map-occurrences (function (r recurrence) &key from to count)
  (let ((start (or (recurrence-start r) from)))
    (unless start
      (error 'datetime-arithmetic-error
             :message "recurrence needs :from on the constructor or on MAP-OCCURRENCES"))
    (when (and (recurrence-count r) (recurrence-until r))
      (error 'datetime-arithmetic-error
             :message "RFC 5545: COUNT and UNTIL must not both be set"))
    (multiple-value-bind (to* count*)
        (%ensure-bound r to count (recurrence-until r) (recurrence-count r))
      (when to* (setf to to*))
      (let* ((from-rd (date-rd (if from
                                   (if (cl:< (date-rd from) (date-rd start)) start from)
                                   start)))
             (to-rd (and to (date-rd to)))
             (rule-left (recurrence-count r))
             (query-left count*)
             (interval (recurrence-interval r))
             (stop nil))
        (ecase (recurrence-freq r)
          (:daily
           (loop for rd from (date-rd start) by interval
                 until (or stop
                           (and to-rd (cl:>= rd to-rd) (null rule-left))
                           (and (recurrence-until r)
                                (cl:> rd (date-rd (recurrence-until r)))))
                 do (multiple-value-setq (rule-left query-left stop)
                      (%walk-list function r (%daily-candidates r rd)
                                  from-rd to-rd rule-left query-left))))
          (:weekly
           (let ((ws0 (week-start-rd start (recurrence-week-start r))))
             (loop for week from 0
                   for week-rd = (cl:+ ws0 (cl:* week 7 interval))
                   until (or stop
                             (and to-rd (cl:>= week-rd to-rd) (null rule-left))
                             (and (recurrence-until r)
                                  (cl:> week-rd (date-rd (recurrence-until r)))))
                   do (multiple-value-setq (rule-left query-left stop)
                        (%walk-list function r (%weekly-candidates r week-rd)
                                    from-rd to-rd rule-left query-left)))))
          (:monthly
           (let ((sy (date-year start)) (sm (date-month start)))
             (loop for i from 0
                   for ym = (cl:+ (cl:* sy 12) sm -1 (cl:* i interval))
                   for year = (floor ym 12)
                   for month = (cl:1+ (mod ym 12))
                   for first-rd = (fixed-from-date +gregorian+ year month 1)
                   until (or stop
                             (and to-rd (cl:>= first-rd to-rd) (null rule-left))
                             (and (recurrence-until r)
                                  (cl:> first-rd (date-rd (recurrence-until r)))))
                   do (multiple-value-setq (rule-left query-left stop)
                        (%walk-list function r (%month-candidates r year month)
                                    from-rd to-rd rule-left query-left)))))
          (:yearly
           (loop for year from (date-year start) by interval
                 for first-rd = (fixed-from-date +gregorian+ year 1 1)
                 until (or stop
                           (and to-rd (cl:>= first-rd to-rd) (null rule-left))
                           (and (recurrence-until r)
                                (cl:> first-rd (date-rd (recurrence-until r)))))
                 do (multiple-value-setq (rule-left query-left stop)
                      (%walk-list function r (%year-candidates r year)
                                  from-rd to-rd rule-left query-left)))))))))

;;; constructors

(defun %make-recurrence (freq &key (every 1) from until count weekdays
                                monthdays months setpos (week-start :monday))
  (when (and count until)
    (error 'datetime-arithmetic-error
           :message "RFC 5545: COUNT and UNTIL must not both be set"))
  (make-instance 'recurrence
                 :freq freq :interval (%ensure-interval every)
                 :start (%ensure-date from :from)
                 :until (%ensure-date until :until)
                 :count count
                 :weekdays weekdays :monthdays monthdays :months months
                 :setpos (%as-list setpos)
                 :week-start (weekday-number week-start)))

(defun %parse-weekly-on (on)
  (mapcar #'%weekday-spec (%as-list (or on :monday))))

(defun %parse-monthly-on (on start)
  (cond
    ((null on) (values (when start (list (date-day start))) nil))
    ((integerp on) (values (list on) nil))
    ((or (keywordp on)
         (and (consp on) (or (eq (car on) :nth) (eq (car on) :weekday)
                             (member :weekday on))))
     (values nil (list (%weekday-spec on))))
    ((and (consp on) (every #'integerp on)) (values on nil))
    ((consp on)
     (let ((mdays '()) (wds '()))
       (dolist (item on)
         (if (integerp item) (push item mdays) (push (%weekday-spec item) wds)))
       (values (nreverse mdays) (nreverse wds))))
    (t (error 'datetime-arithmetic-error
              :message (format nil "bad monthly :on ~s" on)))))

(defun %parse-yearly-on (on start)
  (labels ((one (clause)
             (cond
               ((annual-date-p clause)
                (values (list (annual-date-month clause))
                        (list (annual-date-day clause)) nil))
               ((and (consp clause) (or (getf clause :month) (getf clause :day)
                                        (getf clause :weekday)))
                (values (let ((m (getf clause :month))) (and m (list m)))
                        (let ((d (getf clause :day))) (and d (list d)))
                        (let ((wd (getf clause :weekday)))
                          (and wd (list (%weekday-spec
                                         (if (getf clause :nth)
                                             (list :weekday wd :nth (getf clause :nth))
                                             wd)))))))
               (t (error 'datetime-arithmetic-error
                         :message (format nil "bad yearly :on ~s" clause))))))
    (cond
      ((null on)
       (if start (values (list (date-month start)) (list (date-day start)) nil)
           (values nil nil nil)))
      ((annual-date-p on) (one on))
      ((and (consp on) (or (getf on :month) (getf on :day) (getf on :weekday)))
       (one on))
      ((and (consp on) (consp (car on)))
       (let ((months '()) (mdays '()) (wds '()))
         (dolist (c on)
           (multiple-value-bind (m d w) (one c)
             (setf months (append months m) mdays (append mdays d) wds (append wds w))))
         (values months mdays wds)))
      (t (error 'datetime-arithmetic-error
                :message (format nil "bad yearly :on ~s" on))))))

(defun daily (&key (every 1) from until count on)
  (%make-recurrence :daily :every every :from from :until until :count count
                    :weekdays (and on (mapcar #'%weekday-spec (%as-list on)))))

(defun weekly (&key (on :monday) (every 1) from until count (week-start :monday))
  (%make-recurrence :weekly :every every :from from :until until :count count
                    :weekdays (%parse-weekly-on on) :week-start week-start))

(defun monthly (&key on (every 1) from until count setpos)
  (multiple-value-bind (mdays wds) (%parse-monthly-on on from)
    (%make-recurrence :monthly :every every :from from :until until :count count
                      :monthdays mdays :weekdays wds :setpos setpos)))

(defun yearly (&key on (every 1) from until count setpos)
  (multiple-value-bind (months mdays wds) (%parse-yearly-on on from)
    (%make-recurrence :yearly :every every :from from :until until :count count
                      :months months :monthdays mdays :weekdays wds :setpos setpos)))

;;; --- combinators / escape hatches ----------------------------------------

(defclass date-set (schedule)
  ((dates :initarg :dates :reader date-set-dates :initform '())))

(defun date-set (&rest dates)
  (make-instance 'date-set
                 :dates (sort (delete-duplicates (copy-list dates) :test #'value=)
                              #'cl:< :key #'date-rd)))

(defmethod schedule-origin ((s date-set)) (first (date-set-dates s)))
(defmethod occurrence-p ((s date-set) (date date))
  (find date (date-set-dates s) :test #'value=))
(defmethod map-occurrences (function (s date-set) &key from to count)
  (let ((from-rd (and from (date-rd from))) (to-rd (and to (date-rd to))) (n 0))
    (dolist (d (date-set-dates s))
      (let ((rd (date-rd d)))
        (when (and (or (null from-rd) (cl:>= rd from-rd))
                   (or (null to-rd) (cl:< rd to-rd)))
          (funcall function d) (cl:incf n)
          (when (and count (cl:>= n count)) (return)))))))

(defclass compound-schedule (schedule)
  ((include :initarg :include :reader compound-include :initform '())
   (exclude :initarg :exclude :reader compound-exclude :initform '())))

(defun schedule-union (&rest schedules)
  (make-instance 'compound-schedule :include schedules))

(defun schedule-except (include &rest excluded)
  (make-instance 'compound-schedule
                 :include (if (listp include) include (list include))
                 :exclude excluded))

(defmethod schedule-origin ((s compound-schedule))
  (let ((origins (remove nil (mapcar #'schedule-origin (compound-include s)))))
    (when origins
      (reduce (lambda (a b) (if (cl:< (date-rd a) (date-rd b)) a b)) origins))))

(defmethod occurrence-p ((s compound-schedule) (date date))
  (and (some (lambda (inc) (occurrence-p inc date)) (compound-include s))
       (not (some (lambda (ex) (occurrence-p ex date)) (compound-exclude s)))))

(defmethod map-occurrences (function (s compound-schedule) &key from to count)
  (multiple-value-bind (to* count*)
      (%ensure-bound s to count nil nil)
    (let ((raw '()) (seen (make-hash-table :test #'eql)))
      (dolist (inc (compound-include s))
        (map-occurrences (lambda (d) (push d raw)) inc :from from :to to* :count nil))
      (let ((n 0))
        (dolist (x (sort raw #'cl:< :key (lambda (x) (date-rd (occurrence-date x)))))
          (let ((d (occurrence-date x)))
            (unless (or (gethash (date-rd d) seen)
                        (some (lambda (ex) (occurrence-p ex d)) (compound-exclude s)))
              (setf (gethash (date-rd d) seen) t)
              (funcall function x) (cl:incf n)
              (when (and count* (cl:>= n count*)) (return)))))))))

(defclass predicate-schedule (schedule)
  ((test :initarg :test :reader predicate-schedule-test)
   (origin :initarg :origin :initform nil :reader schedule-origin))
  (:documentation "Scan each civil day. Escape hatch for business-days etc."))

(defun predicate-schedule (test &key origin)
  "TEST is (DATE) → boolean. Dense scan — use a specialized method when you can."
  (make-instance 'predicate-schedule :test test :origin origin))

(defmethod occurrence-p ((s predicate-schedule) (date date))
  (and (funcall (predicate-schedule-test s) date) t))

(defmethod map-occurrences (function (s predicate-schedule) &key from to count)
  (multiple-value-bind (to* count*)
      (%ensure-bound s to count nil nil)
    (let* ((start (or from (schedule-origin s)))
           (end to*)
           (n 0))
      (unless (and start end)
        (error 'unbounded-schedule :schedule s
               :message "predicate-schedule needs :from and :to"))
      (loop for rd from (date-rd start) below (date-rd end)
            for d = (date-from-rd rd)
            when (funcall (predicate-schedule-test s) d)
              do (funcall function d) (cl:incf n)
                 (when (and count* (cl:>= n count*)) (return))))))

(defclass function-schedule (schedule)
  ((mapper :initarg :mapper :reader function-schedule-mapper)
   (origin :initarg :origin :initform nil :reader schedule-origin)
   (tester :initarg :tester :initform nil :reader function-schedule-tester))
  (:documentation "MAPPER is (FROM TO) → list of dates/moments. Later rules."))

(defun function-schedule (mapper &key origin tester)
  (make-instance 'function-schedule :mapper mapper :origin origin :tester tester))

(defmethod occurrence-p ((s function-schedule) (date date))
  (if (function-schedule-tester s)
      (funcall (function-schedule-tester s) date)
      (find date (funcall (function-schedule-mapper s) date (date-from-rd (cl:1+ (date-rd date))))
            :key #'occurrence-date :test #'value=)))

(defmethod map-occurrences (function (s function-schedule) &key from to count)
  (multiple-value-bind (to* count*)
      (%ensure-bound s to count nil nil)
    (let ((n 0)
          (from* (or from (schedule-origin s)))
          (end (or to* (and from* (date-from-rd (cl:+ (date-rd from*) 400))))))
      (unless (and from* end)
        (error 'unbounded-schedule :schedule s
               :message "function-schedule needs :from and :to (or :count)"))
      (dolist (x (funcall (function-schedule-mapper s) from* end))
        (funcall function x) (cl:incf n)
        (when (and count* (cl:>= n count*)) (return))))))

(defclass offset-schedule (schedule)
  ((basis :initarg :basis :reader offset-schedule-basis)
   (days :initarg :days :reader offset-schedule-days :type integer))
  (:documentation "Each occurrence of BASIS shifted by DAYS (Good Friday = Easter − 2)."))

(defun offset-schedule (basis days)
  (make-instance 'offset-schedule :basis basis :days days))

(defmethod schedule-origin ((s offset-schedule))
  (let ((o (schedule-origin (offset-schedule-basis s))))
    (and o (date-from-rd (cl:+ (date-rd o) (offset-schedule-days s))))))

(defmethod occurrence-p ((s offset-schedule) (date date))
  (occurrence-p (offset-schedule-basis s)
                (date-from-rd (cl:- (date-rd date) (offset-schedule-days s)))))

(defmethod map-occurrences (function (s offset-schedule) &key from to count)
  (let ((d (offset-schedule-days s)))
    (map-occurrences
     (lambda (x)
       (funcall function
                (date-from-rd (cl:+ (date-rd (occurrence-date x)) d))))
     (offset-schedule-basis s)
     :from (and from (date-from-rd (cl:- (date-rd from) d)))
     :to (and to (date-from-rd (cl:- (date-rd to) d)))
     :count count)))

(defmethod occurrence-p ((ad annual-date) (date date))
  (and (cl:= (annual-date-month ad) (date-month date))
       (cl:= (annual-date-day ad) (date-day date))))

(defmethod map-occurrences (function (ad annual-date) &key from to count)
  (unless (or from to count)
    (%ensure-bound ad from to count nil nil))
  (unless (or from to)
    (error 'unbounded-schedule :schedule ad :message "annual-date needs :from or :to"))
  (let ((y0 (if from (date-year from) (cl:1- (date-year to))))
        (y1 (if to (date-year to) (cl:+ (date-year from) (or count 1))))
        (n 0))
    (loop for year from y0 to y1
          for d = (ignore-errors (annual-date-in-year ad year :overflow :error))
          when (and d
                    (or (null from) (cl:>= (date-rd d) (date-rd from)))
                    (or (null to) (cl:< (date-rd d) (date-rd to))))
            do (funcall function d) (cl:incf n)
               (when (and count (cl:>= n count)) (return)))))

;;; --- RFC 5545 RECUR ------------------------------------------------------

(defun %parse-rfc-date (s)
  "YYYYMMDD or YYYYMMDDTHHMMSS[Z]. Date-level: take the civil date."
  (when (and s (cl:>= (length s) 8) (every #'digit-char-p (subseq s 0 8)))
    (make-date (parse-integer s :start 0 :end 4)
               (parse-integer s :start 4 :end 6)
               (parse-integer s :start 6 :end 8))))

(defun %parse-byday (token)
  (let ((n (length token)))
    (cond
      ((cl:< n 2)
       (error 'datetime-parse-error :input token :message "empty BYDAY"))
      ((and (cl:>= n 3) (or (char= (char token 0) #\+) (char= (char token 0) #\-)
                            (digit-char-p (char token 0))))
       (let* ((cut (if (alpha-char-p (char token 1)) 1
                       (or (position-if #'alpha-char-p token) n)))
              (ord (parse-integer token :end cut))
              (wd (cdr (assoc (subseq token cut) *rfc-weekdays* :test #'string-equal))))
         (unless wd
           (error 'datetime-parse-error :input token :message "bad BYDAY weekday"))
         (cons ord wd)))
      (t
       (or (cdr (assoc token *rfc-weekdays* :test #'string-equal))
           (error 'datetime-parse-error :input token :message "bad BYDAY weekday"))))))

(defun %parse-int-list (s)
  (mapcar #'parse-integer (split-sequence #\, s)))

(defun split-sequence (delim string)
  (let ((acc '()) (start 0) (n (length string)))
    (loop for i from 0 to n
          when (or (cl:= i n) (char= (char string i) delim))
            do (push (subseq string start i) acc)
               (setf start (cl:1+ i)))
    (nreverse acc)))

(defun %rrule-parts (string)
  (let ((body string) (dtstart nil))
    (when (search "DTSTART" string :test #'char-equal)
      (loop for line in (split-sequence #\Newline string)
            for trimmed = (string-trim '(#\Return #\Space #\Tab) line)
            when (and (cl:>= (length trimmed) 8)
                      (string-equal "DTSTART" trimmed :end2 7))
              do (let ((colon (position #\: trimmed)))
                   (setf dtstart (%parse-rfc-date (subseq trimmed (cl:1+ colon)))))
            when (and (cl:>= (length trimmed) 6)
                      (string-equal "RRULE:" trimmed :end2 6))
              do (setf body (subseq trimmed 6))))
    (when (and (cl:>= (length body) 6) (string-equal "RRULE:" body :end2 6))
      (setf body (subseq body 6)))
    (values body dtstart)))

(defun parse-rrule (string &key from)
  "Parse an RFC 5545 RECUR value (`FREQ=…`) or a DTSTART/RRULE block.
   Date-level only. HOURLY / BYHOUR / BYYEARDAY / BYWEEKNO → UNSUPPORTED-RECURRENCE.
   COUNT and UNTIL together → DATETIME-ARITHMETIC-ERROR."
  (multiple-value-bind (body dtstart) (%rrule-parts string)
    (let ((freq nil) (interval 1) (count nil) (until nil) (wkst 1)
          (weekdays '()) (monthdays '()) (months '()) (setpos '())
          (start (or from dtstart)))
      (dolist (part (split-sequence #\; body))
        (when (plusp (length part))
          (let ((eq (position #\= part)))
            (unless eq
              (error 'datetime-parse-error :input string :message "RRULE part missing ="))
            (let ((key (string-upcase (subseq part 0 eq)))
                  (val (subseq part (cl:1+ eq))))
              (cond
                ((string= key "FREQ")
                 (setf freq (cond ((string-equal val "DAILY") :daily)
                                  ((string-equal val "WEEKLY") :weekly)
                                  ((string-equal val "MONTHLY") :monthly)
                                  ((string-equal val "YEARLY") :yearly)
                                  (t (error 'unsupported-recurrence :input string
                                            :message (format nil "FREQ=~a (date-level only)" val))))))
                ((string= key "INTERVAL") (setf interval (parse-integer val)))
                ((string= key "COUNT") (setf count (parse-integer val)))
                ((string= key "UNTIL") (setf until (%parse-rfc-date val)))
                ((string= key "WKST")
                 (setf wkst (or (cdr (assoc val *rfc-weekdays* :test #'string-equal))
                                (error 'datetime-parse-error :input val :message "bad WKST"))))
                ((string= key "BYDAY")
                 (setf weekdays (mapcar #'%parse-byday (split-sequence #\, val))))
                ((string= key "BYMONTHDAY") (setf monthdays (%parse-int-list val)))
                ((string= key "BYMONTH") (setf months (%parse-int-list val)))
                ((string= key "BYSETPOS") (setf setpos (%parse-int-list val)))
                ((string= key "DTSTART") (setf start (%parse-rfc-date val)))
                ((member key '("BYHOUR" "BYMINUTE" "BYSECOND" "BYYEARDAY" "BYWEEKNO")
                         :test #'string=)
                 (error 'unsupported-recurrence :input string
                        :message (format nil "~a not supported (date-level recurrence)" key)))
                (t (error 'datetime-parse-error :input string
                          :message (format nil "unknown RRULE part ~a" key))))))))
      (unless freq
        (error 'datetime-parse-error :input string :message "FREQ is required"))
      (when (and weekdays (some #'consp weekdays)
                 (not (member freq '(:monthly :yearly))))
        (error 'datetime-parse-error :input string
               :message "BYDAY ordinals are only legal with MONTHLY or YEARLY"))
      (%make-recurrence freq :every interval :from start :until until :count count
                        :weekdays (or weekdays nil) :monthdays (or monthdays nil)
                        :months (or months nil) :setpos setpos :week-start wkst))))

(defun %rfc-weekday (n)
  (car (rassoc n *rfc-weekdays*)))

(defun %format-byday (spec)
  (if (consp spec)
      (format nil "~d~a" (car spec) (%rfc-weekday (cdr spec)))
      (%rfc-weekday spec)))

(defun print-rrule (schedule)
  "RFC 5545 RECUR text for a RECURRENCE. Other schedule kinds signal."
  (unless (recurrencep schedule)
    (error 'datetime-arithmetic-error
           :message "PRINT-RRULE only applies to RECURRENCE (not compounds / events)"))
  (with-output-to-string (o)
    (format o "FREQ=~a" (ecase (recurrence-freq schedule)
                          (:daily "DAILY") (:weekly "WEEKLY")
                          (:monthly "MONTHLY") (:yearly "YEARLY")))
    (unless (cl:= 1 (recurrence-interval schedule))
      (format o ";INTERVAL=~d" (recurrence-interval schedule)))
    (when (recurrence-count schedule)
      (format o ";COUNT=~d" (recurrence-count schedule)))
    (when (recurrence-until schedule)
      (let ((d (recurrence-until schedule)))
        (format o ";UNTIL=~4,'0d~2,'0d~2,'0d"
                (date-year d) (date-month d) (date-day d))))
    (unless (cl:= 1 (recurrence-week-start schedule))
      (format o ";WKST=~a" (%rfc-weekday (recurrence-week-start schedule))))
    (when (recurrence-weekdays schedule)
      (format o ";BYDAY=~{~a~^,~}" (mapcar #'%format-byday (recurrence-weekdays schedule))))
    (when (recurrence-monthdays schedule)
      (format o ";BYMONTHDAY=~{~d~^,~}" (recurrence-monthdays schedule)))
    (when (recurrence-months schedule)
      (format o ";BYMONTH=~{~d~^,~}" (recurrence-months schedule)))
    (when (recurrence-setpos schedule)
      (format o ";BYSETPOS=~{~d~^,~}" (recurrence-setpos schedule)))))
